version: '2'

services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: simple-user-manager
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/users-db
      - SPRING_DATASOURCE_USERNAME=momo-postgres
      - SPRING_DATASOURCE_PASSWORD=momo-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'postgres:15-alpine'
    container_name: users-db
    environment:
      - POSTGRES_USER=momo-postgres
      - POSTGRES_PASSWORD=momo-postgres
      - POSTGRES_DB=users-db
